### ISSUE TITLE
Additional tokens for `data_leak`

### ISSUE THREAD

**Issue by nrathaus** [OWASP/OFFAT#105]
I would suggest to add the following to the list we currently have:
1. `google_oauth_token`
2. `google_oauth`
3. `google_b64`
4. `awsBucket`
5. `xoxo-`
(used by slack)
6. `https://outlook.office.com/webhook/`

**Comment by nrathaus** [comment]
https://github.com/OWASP/OFFAT/pull/107/files

**Comment by dmdhrumilmistry** [comment]
closing since PR is merged.
