### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by dmdhrumilmistry** [OWASP/OFFAT#52]
Hi @dmdhrumilmistry . As per your suggestion I have tried using offat with Python 3.11. But Unfortunately I am getting the same error:
<img width="839" alt="image" src="https://github.com/OWASP/OFFAT/assets/110390926/b3114236-7ff6-4229-9bd5-3ec831eb05cd">

_Originally posted by @puriaayush01 in https://github.com/OWASP/OFFAT/issues/45#issuecomment-1931505552_

**Comment by puriaayush01** [comment]
Hi, @dmdhrumilmistry I am sharing the JSON file with you. Please verify from your end as well.
[api.json](https://github.com/OWASP/OFFAT/files/14210002/api.json)

**Comment by dmdhrumilmistry** [comment]
Hey @puriaayush01

The file that you've provided is not a valid openapi/swagger documentation file. I would suggest to review openapi/swagger documentation for creating api documentations.

**Comment by puriaayush01** [comment]
Hey @dmdhrumilmistry . I am using the VAmPi Open API Swagger file to test. Is this not valid?

<img width="960" alt="image" src="https://github.com/OWASP/OFFAT/assets/110390926/0a484065-eb15-4060-9ac6-eb1623e8a37c">
<img width="936" alt="image" src="https://github.com/OWASP/OFFAT/assets/110390926/2bcdc6f7-27d9-4706-aee7-698f0b46b8f0">

**Comment by dmdhrumilmistry** [comment]
> Hey @dmdhrumilmistry . I am using the VAmPi Open API Swagger file to test. Is this not valid?
> <img alt="image" width="960" src="https://private-user-images.githubusercontent.com/110390926/303572892-0a484065-eb15-4060-9ac6-eb1623e8a37c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0ODA5MjQsIm5iZiI6MTcwNzQ4MDYyNCwicGF0aCI6Ii8xMTAzOTA5MjYvMzAzNTcyODkyLTBhNDg0MDY1LWViMTUtNDA2MC05YWM2LWViMTYyM2U4YTM3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQxMjEwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODRlMDRiMmViNDUxMmZmYTBjNjRjYjI2YjJjYzFkNDg2ODc2MmZkMTA4ODNmMzU3MTBmYTAzZjlmMGU1NTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nfaB0YJ2HcAxGlar3rh1z6bICM_LBylkidBxEgbC9Rk"> <img alt="image" width="936" src="https://private-user-images.githubusercontent.com/110390926/303572988-2bcdc6f7-27d9-4706-aee7-698f0b46b8f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0ODA5MjQsIm5iZiI6MTcwNzQ4MDYyNCwicGF0aCI6Ii8xMTAzOTA5MjYvMzAzNTcyOTg4LTJiY2RjNmY3LTI3ZDktNDcwNi1hZWU3LTY5OGYwYjQ2YjhmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQxMjEwMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDY2OTZhM2IyZTkzNWJlMjZhODdmNjA0ZDU5MmNmNjA0MWQ3OTYyYzNmY2EyZDI2ODIzN2I4YjEzZmMyZDFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KHphj4J7SOum_OLx5-ZX5k1Km-qxrWzFVgAoD1sSUj0">

I believe you've mistakenly attached postman documentation. The snippets you've attached is missing server urls so tool doesn't know where to send requests. You need to add server urls to the documentation.

```yaml
servers:
  - url: http://{IP}:{PORT}/{API_BASEPATH}
```

You can use Swagger editor for making necessary changes (It might convert your json file to yaml format) 

You can use the openapi documentation after adding server urls.
