### ISSUE TITLE
Feature : Documentation 

### ISSUE THREAD

**Issue by LasneF** [OWASP/OFFAT#71]
Documentation would requires more details for instance i got 

![image](https://github.com/OWASP/OFFAT/assets/12461661/aded4b03-45fd-49b3-ad71-607ea8817064)

1st lines indicate leak found ; yes but what can of leak ? , still the test passed successfully 

2nd lines says Failed , but not a clear answer about why 

![image](https://github.com/OWASP/OFFAT/assets/12461661/8e9e6411-21fc-48c0-a96d-9d1693043a8c)

having a 200 not clear why it is mentionned as suspicious ?

according to what i understood the datalleak is a parsing of sensitive data such as telephone as part of the returned payload ? 
i got in mine for instance date, jwtToken, PhoneNumberIN, PhoneNumberUS 
is that correct understanding  ? 

it is important to document here what the tooling is doing

**Comment by dmdhrumilmistry** [comment]
> Documentation would requires more details for instance i got
> 
> ![image](https://private-user-images.githubusercontent.com/12461661/318105886-aded4b03-45fd-49b3-ad71-607ea8817064.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzg3NjMsIm5iZiI6MTcxMjIzODQ2MywicGF0aCI6Ii8xMjQ2MTY2MS8zMTgxMDU4ODYtYWRlZDRiMDMtNDVmZC00OWIzLWFkNzEtNjA3ZWE4ODE3MDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDEzNDc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZTU2YTZmOTZiMzJmOWU0MWQxMjE2MzBkM2QxNTdiMDU2MmE2MGVjYzAwNmQzYmNhYTAwYzQ4Y2RhY2MxMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U2DzaRuDYopwgn90huyy1yUkyfI54YS8RpHm-tOiV3U)
> 
> 1st lines indicate leak found ; yes but what can of leak ? , still the test passed successfully
> 
> 2nd lines says Failed , but not a clear answer about why
> 
> ![image](https://private-user-images.githubusercontent.com/12461661/318107553-8e9e6411-21fc-48c0-a96d-9d1693043a8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzg3NjMsIm5iZiI6MTcxMjIzODQ2MywicGF0aCI6Ii8xMjQ2MTY2MS8zMTgxMDc1NTMtOGU5ZTY0MTEtMjFmYy00OGMwLWE5NmQtOWQxNjkzMDQzYThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDEzNDc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlZDJhMzBiOTliMWNkYTcxZmUxZTMzNjMyMzc0NjM2MThkNmU0OTdkNWUyY2Y4NzlkZjRkMDU0ZTkzYTMzMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m8maZNu_lmtA9oL4g_MXSdPI3n6P6iTGpdlXpmpqgtk)
> 
> having a 200 not clear why it is mentionned as suspicious ?
> 
> according to what i understood the datalleak is a parsing of sensitive data such as telephone as part of the returned payload ? i got in mine for instance date, jwtToken, PhoneNumberIN, PhoneNumberUS is that correct understanding ?
> 
> it is important to document here what the tooling is doing

For time being I've separated Data Leak and API test, so currently they're interpreted individually. 

Yes, telephone number could be leading to failure of Data leak test. 

I'll be make necessary changes for data leak tests for be reflected in overall API test results.

**Comment by LasneF** [comment]
May be add as well a filter on the reporting HTML file 

i am still not clear on what this kind of output means 

Test Name:
BOPLA Test
Test Result:
❌ Failed
Result Details:
Endpoint might be vulnerable to BOPLA
Test Response Filter:
STATUS_CODE_FILTER
Data Leak:
No Data Leakage Found

we need to have further details on what STATUS_CODE_FILTER means

**Comment by dmdhrumilmistry** [comment]
> May be add as well a filter on the reporting HTML file
> 
> i am still not clear on what this kind of output means
> 
> Test Name: BOPLA Test Test Result: ❌ Failed Result Details: Endpoint might be vulnerable to BOPLA Test Response Filter: STATUS_CODE_FILTER Data Leak: No Data Leakage Found
> 
> we need to have further details on what STATUS_CODE_FILTER means

HTML report is kinda buggy at the moment and I'm not planning to update it any time soon. There are several challenges while handling HTML reports such as sanitizing and formatting data correctly which can be tricky and If I miss something it can lead to security issues.

`STATUS_CODE_FILTER` is used internally to find indicator of vulnerability in few cases after receiving response from the API server. 

https://github.com/OWASP/OFFAT/blob/ce7086c3a26cb6ba469e6741b0f0f753814240ec/src/offat/tester/post_test_processor.py#L183

I've clarified the usage of `data_leak` and `result` columns in the results table in README.md files for now. 

PR: https://github.com/OWASP/OFFAT/pull/77
